"""
__author__ = "Kevin Chau"
__date-created__ = "2019-03-04"
__date-modified__ = "2019-03-04"
"""

import os

localrules: all, format_for_seurat, build_seurat

configfile: "config.yaml"

# Setup pipeline directories
if not os.path.exists("data"):
    os.makedirs("data")
if not os.path.exists("data/figures"):
    os.makedirs("data/figures")
if not os.path.exists("log"):
    os.makedirs("log")

rule all:
   input: 
        "data/initialMultiCCA.rds"

rule seurat_process:
    input:
        lambda wildcard: 
            f"{config['ids'][wildcard.sample_id]['SEURAT']}"
    output:
        "data/{sample_id}/seurat_processed.rds"
    params:
        nUMI_low = lambda wildcard:
            f"{config['ids'][wildcard.sample_id]['nUMI']['LOW']}",
        nUMI_high = lambda wildcard:
            f"{config['ids'][wildcard.sample_id]['nUMI']['HIGH']}",
        percent_mito_low = lambda wildcard:
            f"{config['ids'][wildcard.sample_id]['percent_mito']['LOW']}",
        percent_mito_high = lambda wildcard:
            f"{config['ids'][wildcard.sample_id]['percent_mito']['HIGH']}"
    script:
        "scripts/seurat_process.R"

rule seurat_combine:
    input:
        expand("data/{sample_id}/seurat_processed.rds", sample_id = config["ids"].keys())
    output:
        "data/initialMultiCCA.rds"
    script:
        "scripts/seurat_combine.R"